// 运动框架
window.requestAnimationFrame = window.requestAnimationFrame || function (fn) {
    return setTimeout(fn, 1000 / 60)
}
window.cancelAnimationFrame = window.cancelAnimationFrame || clearTimeout

let navBtn = document.getElementsByClassName('navBtn'),
    alink = document.getElementsByClassName('alink'),
    topNav = document.getElementsByClassName('topListNav')[0]
let state2 = 0
console.log(topNav.innerHTML)
showNav = function () {
    if (state2 == 0) {
        state2 = 1
        animation(topNav, 'height', 125, 20.5)
        // 点出来得高度
    } else {
        state2 = 0
        animation(topNav, 'height', 0, 60)
    }
}
//运动框架开始
function animation (ele, attr, value, step) {
    value = parseFloat(value)
    step = parseFloat(step)
    var startAttr = parseFloat(getStyle(ele)[attr]), // 拿到要控制的初始属性值
        isDirection = startAttr > value // true : 起始值大（要减step）

    if (isDirection) {
        step = -step 	// 确定方向
    } // 
    fn()
    function fn () {
        startAttr += step
        if (isDirection ? startAttr <= value : startAttr >= value) {
            // 一旦进来 就是达到目标值
            startAttr = value
        } else {
            requestAnimationFrame(fn)
        }
        ele.style[attr] = startAttr + "px"
    }
}

function getStyle (ele) {
    return ele.currentStyle || getComputedStyle(ele)
}
console.log(alink.length)
for (let i = 0; i < alink.length; i++) {
    alink[i].index = i
    alink[i].addEventListener('click', function () {

        alink[i].className = 'alinkActive alink'
    })
}

// 分享
new ClipboardJS('#copyInput', {
    text: function (trigger) {
        return document.getElementById("myInput").value
    }
}).on('success', function (e) {
    alert("复制成功！可直接粘贴发送给QQ或微信好友！")
    e.clearSelection()
}).on('error', function (e) {
    alert('Error!')
})



// swiper
const audio1 = document.getElementById('audio1')
const audio2 = document.getElementById('audio2')
const audio3 = document.getElementById('audio3')
const audio4 = document.getElementById('audio4')
const audio5 = document.getElementById('audio5')
const audio6 = document.getElementById('audio6')
const audio7 = document.getElementById('audio7')
const audio8 = document.getElementById('audio8')
const audio9 = document.getElementById('audio9')
const audio10 = document.getElementById('audio10')
const audio11 = document.getElementById('audio11')
const audio12 = document.getElementById('audio12')
const audio13 = document.getElementById('audio13')
const audio14 = document.getElementById('audio14')
const audio15 = document.getElementById('audio15')
const audio16 = document.getElementById('audio16')
const audio17 = document.getElementById('audio17')
const audio18 = document.getElementById('audio18')
const audio19 = document.getElementById('audio19')
const audio20 = document.getElementById('audio20')
const audio21 = document.getElementById('audio21')
const audio22 = document.getElementById('audio22')
const audio23 = document.getElementById('audio23')
const audio24 = document.getElementById('audio24')
const audio25 = document.getElementById('audio25')
const audio26 = document.getElementById('audio26')
const audio27 = document.getElementById('audio27')
const audio28 = document.getElementById('audio28')
const audio29 = document.getElementById('audio29')
const audio30 = document.getElementById('audio30')
const audio31 = document.getElementById('audio31')
const audio32 = document.getElementById('audio32')
const audio33 = document.getElementById('audio33')
const audio34 = document.getElementById('audio34')
const audio35 = document.getElementById('audio35')
const audio36 = document.getElementById('audio36')
const audio37 = document.getElementById('audio37')
const audio38 = document.getElementById('audio38')
const audio39 = document.getElementById('audio39')
const audio40 = document.getElementById('audio40')
const audio41 = document.getElementById('audio41')
const audio42 = document.getElementById('audio42')
const audio43 = document.getElementById('audio43')
const audio44 = document.getElementById('audio44')
const audio45 = document.getElementById('audio45')
const audio46 = document.getElementById('audio46')
const audio47 = document.getElementById('audio47')
const audio48 = document.getElementById('audio48')
const audio49 = document.getElementById('audio49')
const audio50 = document.getElementById('audio50')
const audio51 = document.getElementById('audio51')
const audio52 = document.getElementById('audio52')
const audio53 = document.getElementById('audio53')
const audio54 = document.getElementById('audio54')
const audio55 = document.getElementById('audio55')
const audio56 = document.getElementById('audio56')
const audio57 = document.getElementById('audio57')
const audio58 = document.getElementById('audio58')
const audio59 = document.getElementById('audio59')
const audio60 = document.getElementById('audio60')
const audio61 = document.getElementById('audio61')
const audio62 = document.getElementById('audio62')
const audio63 = document.getElementById('audio63')
const audio64 = document.getElementById('audio64')
const audio65 = document.getElementById('audio65')
const audio66 = document.getElementById('audio66')
const audio67 = document.getElementById('audio67')
const audio68 = document.getElementById('audio68')
const audio69 = document.getElementById('audio69')
const audio70 = document.getElementById('audio70')
const audio71 = document.getElementById('audio71')
const audio72 = document.getElementById('audio72')
const audio73 = document.getElementById('audio73')
const audio74 = document.getElementById('audio74')
const audio75 = document.getElementById('audio75')
const audio76 = document.getElementById('audio76')
const audio77 = document.getElementById('audio77')
const audio78 = document.getElementById('audio78')
const audio79 = document.getElementById('audio79')
const audio80 = document.getElementById('audio80')
const audio81 = document.getElementById('audio81')
const audio82 = document.getElementById('audio82')
const audio83 = document.getElementById('audio83')
const audio84 = document.getElementById('audio84')
const audio85 = document.getElementById('audio85')
const audio86 = document.getElementById('audio86')
const audio87 = document.getElementById('audio87')
const audio88 = document.getElementById('audio88')
const audio89 = document.getElementById('audio89')
const audio90 = document.getElementById('audio90')
const audio91 = document.getElementById('audio91')
const audio92 = document.getElementById('audio92')
const audio93 = document.getElementById('audio93')
const audio94 = document.getElementById('audio94')
const audio95 = document.getElementById('audio95')
const audio96 = document.getElementById('audio96')
const audio97 = document.getElementById('audio97')
const audio98 = document.getElementById('audio98')
const audio99 = document.getElementById('audio99')
const audio100 = document.getElementById('audio100')
const audio101 = document.getElementById('audio101')
const audio102 = document.getElementById('audio102')
const audio103 = document.getElementById('audio103')
const audio104 = document.getElementById('audio104')
const audio105 = document.getElementById('audio105')
const audio106 = document.getElementById('audio106')
const audio107 = document.getElementById('audio107')
const audio108 = document.getElementById('audio108')
const audio109 = document.getElementById('audio109')
const audio110 = document.getElementById('audio110')
const audio111 = document.getElementById('audio111')
const audio112 = document.getElementById('audio112')
const audio113 = document.getElementById('audio113')
const audio114 = document.getElementById('audio114')
const audio115 = document.getElementById('audio115')
const audio116 = document.getElementById('audio116')
const audio117 = document.getElementById('audio117')
const audio118 = document.getElementById('audio118')
const audio119 = document.getElementById('audio119')
const audio120 = document.getElementById('audio120')
const audio121 = document.getElementById('audio121')
const audio122 = document.getElementById('audio122')
const audio123 = document.getElementById('audio123')
const audio124 = document.getElementById('audio124')
const audio125 = document.getElementById('audio125')
const audio126 = document.getElementById('audio126')
const audio127 = document.getElementById('audio127')
const audio128 = document.getElementById('audio128')
const audio129 = document.getElementById('audio129')
const audio130 = document.getElementById('audio130')
const audio131 = document.getElementById('audio131')
const audio132 = document.getElementById('audio132')
const audio133 = document.getElementById('audio133')
const audio134 = document.getElementById('audio134')
const audio135 = document.getElementById('audio135')
const audio136 = document.getElementById('audio136')
const audio137 = document.getElementById('audio137')
const audio138 = document.getElementById('audio138')
const audio139 = document.getElementById('audio139')
const audio140 = document.getElementById('audio140')
const audio141 = document.getElementById('audio141')
const audio142 = document.getElementById('audio142')
const audio143 = document.getElementById('audio143')
const audio144 = document.getElementById('audio144')
const audio145 = document.getElementById('audio145')
const audio146 = document.getElementById('audio146')
const audio147 = document.getElementById('audio147')
const audio148 = document.getElementById('audio148')
const audio149 = document.getElementById('audio149')
const audio150 = document.getElementById('audio150')
const audio151 = document.getElementById('audio151')
const audio152 = document.getElementById('audio152')
const audio153 = document.getElementById('audio153')
const audio154 = document.getElementById('audio154')
const audio155 = document.getElementById('audio155')
const audio156 = document.getElementById('audio156')
const audio157 = document.getElementById('audio157')
const audio158 = document.getElementById('audio158')
const audio159 = document.getElementById('audio159')
const audio160 = document.getElementById('audio160')
const audio161 = document.getElementById('audio161')
const audio162 = document.getElementById('audio162')
const audio163 = document.getElementById('audio163')
const audio164 = document.getElementById('audio164')
const audio165 = document.getElementById('audio165')
const audio166 = document.getElementById('audio166')
const audio167 = document.getElementById('audio167')
const audio168 = document.getElementById('audio168')
const audio169 = document.getElementById('audio169')
const audio170 = document.getElementById('audio170')
const audio171 = document.getElementById('audio171')
const audio172 = document.getElementById('audio172')
const audio173 = document.getElementById('audio173')
const audio174 = document.getElementById('audio174')
const audio175 = document.getElementById('audio175')
const audio176 = document.getElementById('audio176')
const audio177 = document.getElementById('audio177')
const audio178 = document.getElementById('audio178')
const audio179 = document.getElementById('audio179')
const audio180 = document.getElementById('audio180')
const audio181 = document.getElementById('audio181')
const audio182 = document.getElementById('audio182')
const audio183 = document.getElementById('audio183')
const audio184 = document.getElementById('audio184')
const audio185 = document.getElementById('audio185')
const audio186 = document.getElementById('audio186')
const audio187 = document.getElementById('audio187')
const audio188 = document.getElementById('audio188')
const audio189 = document.getElementById('audio189')
const audio190 = document.getElementById('audio190')
const audio191 = document.getElementById('audio191')
const audio192 = document.getElementById('audio192')
const audio193 = document.getElementById('audio193')
const audio194 = document.getElementById('audio194')
const audio195 = document.getElementById('audio195')
const audio196 = document.getElementById('audio196')
const audio197 = document.getElementById('audio197')
const audio198 = document.getElementById('audio198')
const audio199 = document.getElementById('audio199')
const audio200 = document.getElementById('audio200')
const audio201 = document.getElementById('audio201')
const audio202 = document.getElementById('audio202')
const audio203 = document.getElementById('audio203')
const audio204 = document.getElementById('audio204')
const audio205 = document.getElementById('audio205')
const audio206 = document.getElementById('audio206')
const audio207 = document.getElementById('audio207')
const audio208 = document.getElementById('audio208')
const audio209 = document.getElementById('audio209')
const audio210 = document.getElementById('audio210')
const audio211 = document.getElementById('audio211')
const audio212 = document.getElementById('audio212')
const audio213 = document.getElementById('audio213')
const audio214 = document.getElementById('audio214')
const audio215 = document.getElementById('audio215')
const audio216 = document.getElementById('audio216')
const audio217 = document.getElementById('audio217')
const audio218 = document.getElementById('audio218')
const audio219 = document.getElementById('audio219')
const audio220 = document.getElementById('audio220')
const audio221 = document.getElementById('audio221')
const audio222 = document.getElementById('audio222')
const audio223 = document.getElementById('audio223')
const audio224 = document.getElementById('audio224')
const audio225 = document.getElementById('audio225')
const audio226 = document.getElementById('audio226')
const audio227 = document.getElementById('audio227')
const audio228 = document.getElementById('audio228')
const audio229 = document.getElementById('audio229')
const audio230 = document.getElementById('audio230')
const audio231 = document.getElementById('audio231')
const audio232 = document.getElementById('audio232')
const audio233 = document.getElementById('audio233')
const audio234 = document.getElementById('audio234')
const audio235 = document.getElementById('audio235')
const audio236 = document.getElementById('audio236')
const audio237 = document.getElementById('audio237')
const audio238 = document.getElementById('audio238')
const audio239 = document.getElementById('audio239')
const audio240 = document.getElementById('audio240')
const audio241 = document.getElementById('audio241')
const audio242 = document.getElementById('audio242')
const audio243 = document.getElementById('audio243')
const audio244 = document.getElementById('audio244')
const audio245 = document.getElementById('audio245')
const audio246 = document.getElementById('audio246')
const audio247 = document.getElementById('audio247')
const audio248 = document.getElementById('audio248')
const audio249 = document.getElementById('audio249')
const audio250 = document.getElementById('audio250')
const audio251 = document.getElementById('audio251')
const audio252 = document.getElementById('audio252')
const audio253 = document.getElementById('audio253')
const audio254 = document.getElementById('audio254')
const audio255 = document.getElementById('audio255')
const audio256 = document.getElementById('audio256')
const audio257 = document.getElementById('audio257')
const audio258 = document.getElementById('audio258')
const audio259 = document.getElementById('audio259')
const audio260 = document.getElementById('audio260')
const audio261 = document.getElementById('audio261')
const audio262 = document.getElementById('audio262')
const audio263 = document.getElementById('audio263')
const audio264 = document.getElementById('audio264')
const audio265 = document.getElementById('audio265')
const audio266 = document.getElementById('audio266')
const audio267 = document.getElementById('audio267')
const audio268 = document.getElementById('audio268')
const audio269 = document.getElementById('audio269')
const audio270 = document.getElementById('audio270')
const audio271 = document.getElementById('audio271')
const audio272 = document.getElementById('audio272')
const audio273 = document.getElementById('audio273')
const audio274 = document.getElementById('audio274')
const audio275 = document.getElementById('audio275')
const audio276 = document.getElementById('audio276')
const audio277 = document.getElementById('audio277')
const audio278 = document.getElementById('audio278')
const audio279 = document.getElementById('audio279')
const audio280 = document.getElementById('audio280')
const audio281 = document.getElementById('audio281')
const audio282 = document.getElementById('audio282')
const audio283 = document.getElementById('audio283')
const audio284 = document.getElementById('audio284')
const audio285 = document.getElementById('audio285')
const audio286 = document.getElementById('audio286')
const audio287 = document.getElementById('audio287')
const audio288 = document.getElementById('audio288')
const audio289 = document.getElementById('audio289')
const audio290 = document.getElementById('audio290')
const audio291 = document.getElementById('audio291')
const audio292 = document.getElementById('audio292')
const audio293 = document.getElementById('audio293')
const audio294 = document.getElementById('audio294')
const audio295 = document.getElementById('audio295')
const audio296 = document.getElementById('audio296')
const audio297 = document.getElementById('audio297')
const audio298 = document.getElementById('audio298')
const audio299 = document.getElementById('audio299')
const audio300 = document.getElementById('audio300')

const soundButton1 = document.getElementById('soundButton1')
const soundButton2 = document.getElementById('soundButton2')
const soundButton3 = document.getElementById('soundButton3')
const soundButton4 = document.getElementById('soundButton4')
const soundButton5 = document.getElementById('soundButton5')
const soundButton6 = document.getElementById('soundButton6')
const soundButton7 = document.getElementById('soundButton7')
const soundButton8 = document.getElementById('soundButton8')
const soundButton9 = document.getElementById('soundButton9')
const soundButton10 = document.getElementById('soundButton10')
const soundButton11 = document.getElementById('soundButton11')
const soundButton12 = document.getElementById('soundButton12')
const soundButton13 = document.getElementById('soundButton13')
const soundButton14 = document.getElementById('soundButton14')
const soundButton15 = document.getElementById('soundButton15')
const soundButton16 = document.getElementById('soundButton16')
const soundButton17 = document.getElementById('soundButton17')
const soundButton18 = document.getElementById('soundButton18')
const soundButton19 = document.getElementById('soundButton19')
const soundButton20 = document.getElementById('soundButton20')
const soundButton21 = document.getElementById('soundButton21')
const soundButton22 = document.getElementById('soundButton22')
const soundButton23 = document.getElementById('soundButton23')
const soundButton24 = document.getElementById('soundButton24')
const soundButton25 = document.getElementById('soundButton25')
const soundButton26 = document.getElementById('soundButton26')
const soundButton27 = document.getElementById('soundButton27')
const soundButton28 = document.getElementById('soundButton28')
const soundButton29 = document.getElementById('soundButton29')
const soundButton30 = document.getElementById('soundButton30')
const soundButton31 = document.getElementById('soundButton31')
const soundButton32 = document.getElementById('soundButton32')
const soundButton33 = document.getElementById('soundButton33')
const soundButton34 = document.getElementById('soundButton34')
const soundButton35 = document.getElementById('soundButton35')
const soundButton36 = document.getElementById('soundButton36')
const soundButton37 = document.getElementById('soundButton37')
const soundButton38 = document.getElementById('soundButton38')
const soundButton39 = document.getElementById('soundButton39')
const soundButton40 = document.getElementById('soundButton40')
const soundButton41 = document.getElementById('soundButton41')
const soundButton42 = document.getElementById('soundButton42')
const soundButton43 = document.getElementById('soundButton43')
const soundButton44 = document.getElementById('soundButton44')
const soundButton45 = document.getElementById('soundButton45')
const soundButton46 = document.getElementById('soundButton46')
const soundButton47 = document.getElementById('soundButton47')
const soundButton48 = document.getElementById('soundButton48')
const soundButton49 = document.getElementById('soundButton49')
const soundButton50 = document.getElementById('soundButton50')
const soundButton51 = document.getElementById('soundButton51')
const soundButton52 = document.getElementById('soundButton52')
const soundButton53 = document.getElementById('soundButton53')
const soundButton54 = document.getElementById('soundButton54')
const soundButton55 = document.getElementById('soundButton55')
const soundButton56 = document.getElementById('soundButton56')
const soundButton57 = document.getElementById('soundButton57')
const soundButton58 = document.getElementById('soundButton58')
const soundButton59 = document.getElementById('soundButton59')
const soundButton60 = document.getElementById('soundButton60')
const soundButton61 = document.getElementById('soundButton61')
const soundButton62 = document.getElementById('soundButton62')
const soundButton63 = document.getElementById('soundButton63')
const soundButton64 = document.getElementById('soundButton64')
const soundButton65 = document.getElementById('soundButton65')
const soundButton66 = document.getElementById('soundButton66')
const soundButton67 = document.getElementById('soundButton67')
const soundButton68 = document.getElementById('soundButton68')
const soundButton69 = document.getElementById('soundButton69')
const soundButton70 = document.getElementById('soundButton70')
const soundButton71 = document.getElementById('soundButton71')
const soundButton72 = document.getElementById('soundButton72')
const soundButton73 = document.getElementById('soundButton73')
const soundButton74 = document.getElementById('soundButton74')
const soundButton75 = document.getElementById('soundButton75')
const soundButton76 = document.getElementById('soundButton76')
const soundButton77 = document.getElementById('soundButton77')
const soundButton78 = document.getElementById('soundButton78')
const soundButton79 = document.getElementById('soundButton79')
const soundButton80 = document.getElementById('soundButton80')
const soundButton81 = document.getElementById('soundButton81')
const soundButton82 = document.getElementById('soundButton82')
const soundButton83 = document.getElementById('soundButton83')
const soundButton84 = document.getElementById('soundButton84')
const soundButton85 = document.getElementById('soundButton85')
const soundButton86 = document.getElementById('soundButton86')
const soundButton87 = document.getElementById('soundButton87')
const soundButton88 = document.getElementById('soundButton88')
const soundButton89 = document.getElementById('soundButton89')
const soundButton90 = document.getElementById('soundButton90')
const soundButton91 = document.getElementById('soundButton91')
const soundButton92 = document.getElementById('soundButton92')
const soundButton93 = document.getElementById('soundButton93')
const soundButton94 = document.getElementById('soundButton94')
const soundButton95 = document.getElementById('soundButton95')
const soundButton96 = document.getElementById('soundButton96')
const soundButton97 = document.getElementById('soundButton97')
const soundButton98 = document.getElementById('soundButton98')
const soundButton99 = document.getElementById('soundButton99')
const soundButton100 = document.getElementById('soundButton100')
const soundButton101 = document.getElementById('soundButton101')
const soundButton102 = document.getElementById('soundButton102')
const soundButton103 = document.getElementById('soundButton103')
const soundButton104 = document.getElementById('soundButton104')
const soundButton105 = document.getElementById('soundButton105')
const soundButton106 = document.getElementById('soundButton106')
const soundButton107 = document.getElementById('soundButton107')
const soundButton108 = document.getElementById('soundButton108')
const soundButton109 = document.getElementById('soundButton109')
const soundButton110 = document.getElementById('soundButton110')
const soundButton111 = document.getElementById('soundButton111')
const soundButton112 = document.getElementById('soundButton112')
const soundButton113 = document.getElementById('soundButton113')
const soundButton114 = document.getElementById('soundButton114')
const soundButton115 = document.getElementById('soundButton115')
const soundButton116 = document.getElementById('soundButton116')
const soundButton117 = document.getElementById('soundButton117')
const soundButton118 = document.getElementById('soundButton118')
const soundButton119 = document.getElementById('soundButton119')
const soundButton120 = document.getElementById('soundButton120')
const soundButton121 = document.getElementById('soundButton121')
const soundButton122 = document.getElementById('soundButton122')
const soundButton123 = document.getElementById('soundButton123')
const soundButton124 = document.getElementById('soundButton124')
const soundButton125 = document.getElementById('soundButton125')
const soundButton126 = document.getElementById('soundButton126')
const soundButton127 = document.getElementById('soundButton127')
const soundButton128 = document.getElementById('soundButton128')
const soundButton129 = document.getElementById('soundButton129')
const soundButton130 = document.getElementById('soundButton130')
const soundButton131 = document.getElementById('soundButton131')
const soundButton132 = document.getElementById('soundButton132')
const soundButton133 = document.getElementById('soundButton133')
const soundButton134 = document.getElementById('soundButton134')
const soundButton135 = document.getElementById('soundButton135')
const soundButton136 = document.getElementById('soundButton136')
const soundButton137 = document.getElementById('soundButton137')
const soundButton138 = document.getElementById('soundButton138')
const soundButton139 = document.getElementById('soundButton139')
const soundButton140 = document.getElementById('soundButton140')
const soundButton141 = document.getElementById('soundButton141')
const soundButton142 = document.getElementById('soundButton142')
const soundButton143 = document.getElementById('soundButton143')
const soundButton144 = document.getElementById('soundButton144')
const soundButton145 = document.getElementById('soundButton145')
const soundButton146 = document.getElementById('soundButton146')
const soundButton147 = document.getElementById('soundButton147')
const soundButton148 = document.getElementById('soundButton148')
const soundButton149 = document.getElementById('soundButton149')
const soundButton150 = document.getElementById('soundButton150')
const soundButton151 = document.getElementById('soundButton151')
const soundButton152 = document.getElementById('soundButton152')
const soundButton153 = document.getElementById('soundButton153')
const soundButton154 = document.getElementById('soundButton154')
const soundButton155 = document.getElementById('soundButton155')
const soundButton156 = document.getElementById('soundButton156')
const soundButton157 = document.getElementById('soundButton157')
const soundButton158 = document.getElementById('soundButton158')
const soundButton159 = document.getElementById('soundButton159')
const soundButton160 = document.getElementById('soundButton160')
const soundButton161 = document.getElementById('soundButton161')
const soundButton162 = document.getElementById('soundButton162')
const soundButton163 = document.getElementById('soundButton163')
const soundButton164 = document.getElementById('soundButton164')
const soundButton165 = document.getElementById('soundButton165')
const soundButton166 = document.getElementById('soundButton166')
const soundButton167 = document.getElementById('soundButton167')
const soundButton168 = document.getElementById('soundButton168')
const soundButton169 = document.getElementById('soundButton169')
const soundButton170 = document.getElementById('soundButton170')
const soundButton171 = document.getElementById('soundButton171')
const soundButton172 = document.getElementById('soundButton172')
const soundButton173 = document.getElementById('soundButton173')
const soundButton174 = document.getElementById('soundButton174')
const soundButton175 = document.getElementById('soundButton175')
const soundButton176 = document.getElementById('soundButton176')
const soundButton177 = document.getElementById('soundButton177')
const soundButton178 = document.getElementById('soundButton178')
const soundButton179 = document.getElementById('soundButton179')
const soundButton180 = document.getElementById('soundButton180')
const soundButton181 = document.getElementById('soundButton181')
const soundButton182 = document.getElementById('soundButton182')
const soundButton183 = document.getElementById('soundButton183')
const soundButton184 = document.getElementById('soundButton184')
const soundButton185 = document.getElementById('soundButton185')
const soundButton186 = document.getElementById('soundButton186')
const soundButton187 = document.getElementById('soundButton187')
const soundButton188 = document.getElementById('soundButton188')
const soundButton189 = document.getElementById('soundButton189')
const soundButton190 = document.getElementById('soundButton190')
const soundButton191 = document.getElementById('soundButton191')
const soundButton192 = document.getElementById('soundButton192')
const soundButton193 = document.getElementById('soundButton193')
const soundButton194 = document.getElementById('soundButton194')
const soundButton195 = document.getElementById('soundButton195')
const soundButton196 = document.getElementById('soundButton196')
const soundButton197 = document.getElementById('soundButton197')
const soundButton198 = document.getElementById('soundButton198')
const soundButton199 = document.getElementById('soundButton199')
const soundButton200 = document.getElementById('soundButton200')
const soundButton201 = document.getElementById('soundButton201')
const soundButton202 = document.getElementById('soundButton202')
const soundButton203 = document.getElementById('soundButton203')
const soundButton204 = document.getElementById('soundButton204')
const soundButton205 = document.getElementById('soundButton205')
const soundButton206 = document.getElementById('soundButton206')
const soundButton207 = document.getElementById('soundButton207')
const soundButton208 = document.getElementById('soundButton208')
const soundButton209 = document.getElementById('soundButton209')
const soundButton210 = document.getElementById('soundButton210')
const soundButton211 = document.getElementById('soundButton211')
const soundButton212 = document.getElementById('soundButton212')
const soundButton213 = document.getElementById('soundButton213')
const soundButton214 = document.getElementById('soundButton214')
const soundButton215 = document.getElementById('soundButton215')
const soundButton216 = document.getElementById('soundButton216')
const soundButton217 = document.getElementById('soundButton217')
const soundButton218 = document.getElementById('soundButton218')
const soundButton219 = document.getElementById('soundButton219')
const soundButton220 = document.getElementById('soundButton220')
const soundButton221 = document.getElementById('soundButton221')
const soundButton222 = document.getElementById('soundButton222')
const soundButton223 = document.getElementById('soundButton223')
const soundButton224 = document.getElementById('soundButton224')
const soundButton225 = document.getElementById('soundButton225')
const soundButton226 = document.getElementById('soundButton226')
const soundButton227 = document.getElementById('soundButton227')
const soundButton228 = document.getElementById('soundButton228')
const soundButton229 = document.getElementById('soundButton229')
const soundButton230 = document.getElementById('soundButton230')
const soundButton231 = document.getElementById('soundButton231')
const soundButton232 = document.getElementById('soundButton232')
const soundButton233 = document.getElementById('soundButton233')
const soundButton234 = document.getElementById('soundButton234')
const soundButton235 = document.getElementById('soundButton235')
const soundButton236 = document.getElementById('soundButton236')
const soundButton237 = document.getElementById('soundButton237')
const soundButton238 = document.getElementById('soundButton238')
const soundButton239 = document.getElementById('soundButton239')
const soundButton240 = document.getElementById('soundButton240')
const soundButton241 = document.getElementById('soundButton241')
const soundButton242 = document.getElementById('soundButton242')
const soundButton243 = document.getElementById('soundButton243')
const soundButton244 = document.getElementById('soundButton244')
const soundButton245 = document.getElementById('soundButton245')
const soundButton246 = document.getElementById('soundButton246')
const soundButton247 = document.getElementById('soundButton247')
const soundButton248 = document.getElementById('soundButton248')
const soundButton249 = document.getElementById('soundButton249')
const soundButton250 = document.getElementById('soundButton250')
const soundButton251 = document.getElementById('soundButton251')
const soundButton252 = document.getElementById('soundButton252')
const soundButton253 = document.getElementById('soundButton253')
const soundButton254 = document.getElementById('soundButton254')
const soundButton255 = document.getElementById('soundButton255')
const soundButton256 = document.getElementById('soundButton256')
const soundButton257 = document.getElementById('soundButton257')
const soundButton258 = document.getElementById('soundButton258')
const soundButton259 = document.getElementById('soundButton259')
const soundButton260 = document.getElementById('soundButton260')
const soundButton261 = document.getElementById('soundButton261')
const soundButton262 = document.getElementById('soundButton262')
const soundButton263 = document.getElementById('soundButton263')
const soundButton264 = document.getElementById('soundButton264')
const soundButton265 = document.getElementById('soundButton265')
const soundButton266 = document.getElementById('soundButton266')
const soundButton267 = document.getElementById('soundButton267')
const soundButton268 = document.getElementById('soundButton268')
const soundButton269 = document.getElementById('soundButton269')
const soundButton270 = document.getElementById('soundButton270')
const soundButton271 = document.getElementById('soundButton271')
const soundButton272 = document.getElementById('soundButton272')
const soundButton273 = document.getElementById('soundButton273')
const soundButton274 = document.getElementById('soundButton274')
const soundButton275 = document.getElementById('soundButton275')
const soundButton276 = document.getElementById('soundButton276')
const soundButton277 = document.getElementById('soundButton277')
const soundButton278 = document.getElementById('soundButton278')
const soundButton279 = document.getElementById('soundButton279')
const soundButton280 = document.getElementById('soundButton280')
const soundButton281 = document.getElementById('soundButton281')
const soundButton282 = document.getElementById('soundButton282')
const soundButton283 = document.getElementById('soundButton283')
const soundButton284 = document.getElementById('soundButton284')
const soundButton285 = document.getElementById('soundButton285')
const soundButton286 = document.getElementById('soundButton286')
const soundButton287 = document.getElementById('soundButton287')
const soundButton288 = document.getElementById('soundButton288')
const soundButton289 = document.getElementById('soundButton289')
const soundButton290 = document.getElementById('soundButton290')
const soundButton291 = document.getElementById('soundButton291')
const soundButton292 = document.getElementById('soundButton292')
const soundButton293 = document.getElementById('soundButton293')
const soundButton294 = document.getElementById('soundButton294')
const soundButton295 = document.getElementById('soundButton295')
const soundButton296 = document.getElementById('soundButton296')
const soundButton297 = document.getElementById('soundButton297')
const soundButton298 = document.getElementById('soundButton298')
const soundButton299 = document.getElementById('soundButton299')
const soundButton300 = document.getElementById('soundButton300')

let audioInstances = []

soundButton1.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio1.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton2.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio2.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton3.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio3.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton4.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio4.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton5.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio5.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton6.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio6.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton7.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio7.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton8.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio8.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton9.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio9.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton10.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio10.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton11.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio11.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton12.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio12.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton13.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio13.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton14.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio14.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton15.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio15.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton16.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio16.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton17.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio17.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton18.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio18.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton19.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio19.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton20.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio20.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton21.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio21.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton22.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio22.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton23.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio23.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton24.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio24.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton25.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio25.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton26.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio26.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton27.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio27.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton28.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio28.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton29.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio29.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton30.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio30.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton31.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio31.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton32.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio32.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton33.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio33.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton34.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio34.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton35.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio35.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton36.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio36.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton37.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio37.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton38.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio38.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton39.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio39.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton40.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio40.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton41.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio41.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton42.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio42.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton43.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio43.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton44.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio44.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton45.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio45.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton46.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio46.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton47.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio47.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton48.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio48.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton49.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio49.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton50.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio50.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton51.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio51.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton52.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio52.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton53.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio53.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton54.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio54.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton55.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio55.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton56.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio56.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton57.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio57.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton58.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio58.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton59.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio59.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton60.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio60.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton61.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio61.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton62.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio62.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton63.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio63.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton64.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio64.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton65.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio65.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton66.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio66.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton67.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio67.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton68.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio68.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton69.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio69.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton70.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio70.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton71.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio71.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton72.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio72.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton73.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio73.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton74.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio74.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton75.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio75.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton76.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio76.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton77.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio77.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton78.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio78.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton79.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio79.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton80.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio80.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton81.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio81.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton82.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio82.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton83.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio83.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton84.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio84.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton85.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio85.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton86.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio86.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton87.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio87.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton88.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio88.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton89.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio89.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton90.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio90.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton91.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio91.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton92.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio92.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton93.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio93.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton94.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio94.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton95.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio95.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton96.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio96.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton97.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio97.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton98.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio98.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton99.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio99.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton100.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio100.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton101.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio101.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton102.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio102.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton103.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio103.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton104.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio104.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton105.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio105.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton106.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio106.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton107.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio107.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton108.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio108.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton109.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio109.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton110.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio110.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton111.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio111.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton112.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio112.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton113.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio113.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton114.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio114.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton115.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio115.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton116.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio116.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton117.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio117.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton118.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio118.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton119.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio119.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton120.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio120.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton121.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio121.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton122.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio122.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton123.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio123.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton124.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio124.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton125.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio125.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton126.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio126.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton127.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio127.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton128.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio128.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton129.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio129.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton130.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio130.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton131.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio131.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton132.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio132.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton133.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio133.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton134.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio134.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton135.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio135.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton136.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio136.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton137.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio137.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton138.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio138.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton139.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio139.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton140.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio140.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton141.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio141.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton142.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio142.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton143.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio143.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton144.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio144.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton145.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio145.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton146.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio146.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton147.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio147.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton148.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio148.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton149.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio149.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton150.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio150.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton151.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio151.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton152.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio152.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton153.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio153.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton154.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio154.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton155.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio155.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton156.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio156.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton157.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio157.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton158.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio158.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton159.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio159.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton160.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio160.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton161.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio161.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton162.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio162.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton163.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio163.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton164.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio164.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton165.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio165.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton166.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio166.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton167.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio167.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton168.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio168.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton169.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio169.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton170.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio170.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton171.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio171.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton172.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio172.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton173.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio173.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton174.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio174.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton175.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio175.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton176.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio176.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton177.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio177.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton178.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio178.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton179.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio179.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton180.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio180.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton181.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio181.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton182.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio182.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton183.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio183.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton184.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio184.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton185.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio185.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton186.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio186.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton187.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio187.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton188.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio188.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton189.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio189.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton190.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio190.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton191.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio191.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton192.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio192.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton193.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio193.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton194.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio194.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton195.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio195.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton196.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio196.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton197.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio197.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton198.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio198.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton199.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio199.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton200.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio200.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton201.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio201.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton202.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio202.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton203.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio203.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton204.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio204.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton205.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio205.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton206.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio206.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton207.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio207.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton208.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio208.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton209.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio209.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton210.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio210.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton211.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio211.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton212.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio212.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton213.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio213.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton214.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio214.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton215.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio215.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton216.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio216.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton217.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio217.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton218.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio218.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton219.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio219.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton220.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio220.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton221.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio221.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton222.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio222.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton223.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio223.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton224.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio224.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton225.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio225.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton226.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio226.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton227.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio227.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton228.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio228.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton229.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio229.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton230.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio230.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton231.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio231.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton232.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio232.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton233.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio233.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton234.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio234.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton235.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio235.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton236.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio236.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton237.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio237.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton238.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio238.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton239.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio239.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton240.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio240.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton241.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio241.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton242.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio242.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton243.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio243.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton244.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio244.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton245.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio245.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton246.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio246.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton247.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio247.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton248.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio248.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton249.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio249.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton250.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio250.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton251.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio251.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton252.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio252.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton253.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio253.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton254.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio254.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton255.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio255.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton256.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio256.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton257.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio257.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton258.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio258.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton259.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio259.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton260.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio260.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton261.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio261.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton262.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio262.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton263.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio263.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton264.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio264.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton265.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio265.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton266.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio266.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton267.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio267.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton268.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio268.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton269.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio269.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton270.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio270.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton271.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio271.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton272.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio272.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton273.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio273.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton274.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio274.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton275.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio275.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton276.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio276.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton277.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio277.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton278.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio278.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton279.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio279.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton280.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio280.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton281.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio281.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton282.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio282.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton283.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio283.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton284.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio284.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton285.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio285.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton286.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio286.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton287.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio287.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton288.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio288.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton289.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio289.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton290.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio290.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton291.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio291.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton292.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio292.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton293.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio293.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton294.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio294.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton295.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio295.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton296.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio296.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton297.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio297.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton298.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio298.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton299.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio299.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})
soundButton300.addEventListener('click', () => {
    const newAudioInstance = new Audio(audio300.src)
    audioInstances.push(newAudioInstance)
    newAudioInstance.play()
})